- hosts: all
  become: yes
  vars: 
    allnodes: 
      - node1.vm.net
      - node2.vm.net
      - node3.vm.net
  roles:
    - basic
    - gluster
  tasks:
    - name: show message
      debug: 
        msg: "ah, its ok"

