- hosts: all
  become: yes
  tasks:
    - name: show message
      debug: 
        msg: "ah, its ok"
    
    - name: ensure disk partition exists
      parted:
        device: /dev/sdb
        number: 1
        state: present

    - name: ensure filesustem on partition
      filesystem:
       fstype: xfs
       dev: /dev/sdb1

    - name: ensure partition mounted
      mount:
        path: /mnt
        src: /dev/sdb1
        fstype: xfs
        state: mounted

    - name: ensure firewall stopped
      systemd:
        name: firewalld
        enabled: no
        state: stopped

    - name: install glusterfs
      dnf:
        name: 
          - glusterfs-server
        state: latest

    - name: ensure gluster started
      systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - glusterd
        - glusterfsd
        - glusterfssharedstorage
    
    - name: ensure peers connected
      gluster.gluster.gluster_peer:
        state: present
        nodes:
          - node1.vm.net
          - node2.vm.net
          - node3.vm.net

    - name: ensure bricks dirs
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /mnt/brick  

    - name: ensure volume created
      gluster.gluster.gluster_volume:
        state: present
        name: gv1
        bricks: /mnt/brick
        rebalance: yes
        cluster:
          - node1.vm.net
          - node2.vm.net
          - node3.vm.net
      run_once: true
